import DefaultSideBar from "./DefaultSideBar"; // DefaultSideBar 컴포넌트를 import 합니다.

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="flex flex-col lg:flex-row min-h-screen">
          <DefaultSideBar />
          {children}
        </section>
      </body>
    </html>
  );
}
