import DefaultSideBar from "./DefaultSideBar"; // DefaultSideBar 컴포넌트를 import 합니다.

import { Inter } from "next/font/google";
import "./globals.css";
import { authOptions } from "@/pages/api/auth/[...nextauth].js";
import { getServerSession } from "next-auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="flex flex-col lg:flex-row min-h-screen">
          <DefaultSideBar session={session} />
          <main className="flex-1 overflow-y-auto">{children}</main>
        </section>
      </body>
    </html>
  );
}
