/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OXsR0JqkFbv
 */
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function Component() {
  return (
    (<section key="1" className="flex flex-col lg:flex-row min-h-screen">
      <aside className="w-full lg:w-64 border-r bg-gray-100 dark:bg-gray-800">
        <div className="flex items-center justify-between px-6 py-4 border-b">
          <span className="text-lg font-semibold">UserComm</span>
          <Button size="icon" variant="ghost">
            <MenuIcon className="h-6 w-6" />
          </Button>
        </div>
        <nav className="px-6 py-4 space-y-2">
          <Link
            className="flex items-center space-x-2 text-gray-500 hover:text-gray-900 dark:hover:text-gray-50"
            href="#">
            <HomeIcon className="h-5 w-5" />
            <span>Home</span>
          </Link>
          <Link
            className="flex items-center space-x-2 text-gray-500 hover:text-gray-900 dark:hover:text-gray-50"
            href="#">
            <UsersIcon className="h-5 w-5" />
            <span>Users</span>
          </Link>
          <Link
            className="flex items-center space-x-2 text-gray-500 hover:text-gray-900 dark:hover:text-gray-50"
            href="#">
            <SettingsIcon className="h-5 w-5" />
            <span>Settings</span>
          </Link>
          <Link
            className="flex items-center space-x-2 text-gray-500 hover:text-gray-900 dark:hover:text-gray-50"
            href="#">
            <ListIcon className="h-5 w-5" />
            <span>List Home</span>
          </Link>
        </nav>
      </aside>
      <main className="flex-1 overflow-y-auto">
        <header className="flex items-center justify-between px-6 py-4 border-b">
          <h1 className="text-lg font-semibold">New Post</h1>
        </header>
        <div className="px-6 py-4">
          <form className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="postTitle">Title</Label>
              <Input id="postTitle" placeholder="Enter your post title" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="postContent">Content</Label>
              <Textarea
                className="min-h-[150px]"
                id="postContent"
                placeholder="Write your post content here..." />
            </div>
            <div className="space-y-2">
              <Label htmlFor="postImage">Image URL</Label>
              <Input id="postImage" placeholder="Enter image URL" type="url" />
            </div>
            <Button type="submit">Publish Post</Button>
          </form>
        </div>
      </main>
    </section>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function HomeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>)
  );
}


function UsersIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>)
  );
}


function SettingsIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>)
  );
}


function ListIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="8" x2="21" y1="6" y2="6" />
      <line x1="8" x2="21" y1="12" y2="12" />
      <line x1="8" x2="21" y1="18" y2="18" />
      <line x1="3" x2="3.01" y1="6" y2="6" />
      <line x1="3" x2="3.01" y1="12" y2="12" />
      <line x1="3" x2="3.01" y1="18" y2="18" />
    </svg>)
  );
}
